services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=human-beings
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"