server:
  port: 12345
  ssl:
    enabled: true
    key-store: classpath:keystore/hero-service.p12
    key-store-password: changeit
    key-password: changeit
    key-store-type: PKCS12
    key-alias: hero-service
    trust-store: classpath:keystore/truststore.p12
    trust-store-password: changeit
    trust-store-type: PKCS12
    client-auth: none

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh