server:
  port: ${PORT:0}
  ssl:
    enabled: true
    key-store: classpath:keystore/hero-service.jks
    key-store-password: changeit
    key-password: changeit
    key-store-type: JKS
    key-alias: hero-service
    trust-store: classpath:keystore/truststore.jks
    trust-store-password: changeit
    trust-store-type: JKS
    client-auth: none

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh

humanbeing:
  service:
    url: https://localhost:15478