spring:
  application:
    name: discovery-service

server:
  port: 8761
  ssl:
    enabled: true
    key-store: classpath:keystore/discovery-service.p12
    key-store-password: changeit
    key-password: changeit
    key-store-type: PKCS12
    key-alias: discovery-service
    trust-store: classpath:keystore/truststore.p12
    trust-store-password: changeit
    trust-store-type: PKCS12
    client-auth: need

eureka:
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://localhost:8761/eureka
  instance:
    hostname: localhost
    secure-port-enabled: true
    non-secure-port-enabled: false
    secure-port: 8761